spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/authDb"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
  app:
    name: "authentication with spring by arridhaamrad"
    jwt-secret: "ari_ganteng"
    jwt-expiration-ms: 10000